#!/usr/bin/env python3
"""Batch EAGLE3 inference with decoding statistics.

Runs EAGLE3 speculative decoding over a range of questions (and optionally
multiple choices per question) and compares it against the naive
autoregressive baseline. For every generation it records:

  * new_tokens       - accepted output tokens
  * tree_steps       - number of draft-verify iterations executed
  * acceptance_lengths - committed tokens for each draft-verify iteration
  * accept_length    - mean of acceptance_lengths for this generation
  * eagle_time       - GPU-synchronized decode-only wall time [s]
  * eagle_tok_s      - EAGLE3 throughput [tokens/s]
  * naive_time       - GPU-synchronized decode-only baseline time [s]
  * naive_tok_s      - naive throughput [tokens/s]
  * speedup          - eagle_tok_s / naive_tok_s

An aggregate summary (total tokens, mean acceptance length, mean tok/s,
decoding speedup, ...) is printed at the end and appended as a final
"summary" record to the output JSONL.
"""

from __future__ import annotations

import argparse
import json
import os
import statistics
import sys
from pathlib import Path

import torch


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "externals" / "EAGLE"))
sys.path.insert(0, str(ROOT / "scripts"))

from common import metrics, rouge  # noqa: E402
from common.input_utils import truncate_input_ids  # noqa: E402
from common.reproducibility import seed_everything  # noqa: E402


EAGLE_LLAMA3_SYSTEM_PROMPT = (
    "You are a helpful, respectful and honest assistant. Always answer as "
    "helpfully as possible, while being safe.  Your answers should not include "
    "any harmful, unethical, racist, sexist, toxic, dangerous, or illegal "
    "content. Please ensure that your responses are socially unbiased and "
    "positive in nature.\n\nIf a question does not make any sense, or is not "
    "factually coherent, explain why instead of answering something not "
    "correct. If you don't know the answer to a question, please don't share "
    "false information."
)


def build_eagle_messages(prompt: str) -> list[dict[str, str]]:
    """Use the system+user chat contract from upstream Llama-3 EAGLE."""

    return [
        {"role": "system", "content": EAGLE_LLAMA3_SYSTEM_PROMPT},
        {"role": "user", "content": prompt},
    ]


def resolve_eagle_tree_config(
    *, total_token: int, depth: int, top_k: int
) -> dict[str, int | bool]:
    """Fit the requested tree size to the nodes generated by EAGLE.

    ``total_token`` includes the already accepted/sample token, while
    ``topK_genrate`` can score only the root ``top_k`` candidates plus
    ``depth`` layers of ``top_k * top_k`` candidates.  Passing a larger
    value makes the upstream ``torch.topk`` call fail with the opaque
    ``selected index k out of range`` error.
    """
    if total_token <= 0:
        raise ValueError("total_token must be positive")
    if depth < 0:
        raise ValueError("depth must be non-negative")
    if top_k <= 0:
        raise ValueError("top_k must be positive")

    max_total_token = 1 + top_k + depth * top_k * top_k
    effective_total_token = min(total_token, max_total_token)
    return {
        "total_token": effective_total_token,
        "max_total_token": max_total_token,
        "adjusted": effective_total_token != total_token,
    }


def load_questions(question_file: Path, begin: int, end: int) -> list[dict]:
    rows = [
        json.loads(line)
        for line in question_file.read_text().splitlines()
        if line.strip()
    ]
    selected = rows[begin:end]
    if not selected:
        raise ValueError(f"No question in range [{begin}, {end}) from {question_file}")
    return selected


def build_input_ids(tokenizer, prompt: str, device) -> torch.Tensor:
    return tokenizer.apply_chat_template(
        build_eagle_messages(prompt),
        tokenize=True,
        add_generation_prompt=True,
        enable_thinking=False,
        return_tensors="pt",
        return_dict=False,
    ).to(device)


def timed_generate(
    model,
    input_ids: torch.Tensor,
    temperature: float,
    max_new_tokens: int,
    total_token: int,
    spec: bool,
    is_llama3: bool = True,
    include_phase_timings: bool = False,
) -> tuple:
    """Run EAGLE (spec=True) or naive (spec=False) decoding.

    The legacy return shape is kept unless ``include_phase_timings`` is true.
    In the latter case the model also returns a canonical prefill/decode/e2e
    timing dictionary. For EAGLE, acceptance_lengths contains the number of
    output tokens committed by each draft-verify iteration (accepted draft
    tokens plus the target fallback token).
    """
    max_length = input_ids.shape[1] + max_new_tokens + total_token + 32
    if spec:
        results = model.eagenerate(
            input_ids,
            temperature=temperature,
            max_new_tokens=max_new_tokens,
            max_length=max_length,
            log=True,
            return_stats=True,
            return_phase_timings=include_phase_timings,
            is_llama3=is_llama3,
        )
        if include_phase_timings:
            output_ids, _, idx, elapsed, acceptance_lengths, phase_timings = results
        else:
            output_ids, _, idx, elapsed, acceptance_lengths = results
            phase_timings = None
        steps = len(acceptance_lengths)
    else:
        results = model.naivegenerate(
            input_ids,
            temperature=temperature,
            max_new_tokens=max_new_tokens,
            max_length=max_length,
            log=True,
            return_stats=True,
            return_phase_timings=include_phase_timings,
            is_llama3=is_llama3,
        )
        if include_phase_timings:
            output_ids, new_tokens, idx, elapsed, phase_timings = results
        else:
            output_ids, new_tokens, idx, elapsed = results
            phase_timings = None
        steps = int(idx) + 1
        acceptance_lengths = []

    # Use the returned sequence as the source of truth after max-token
    # truncation, rather than relying on the internal loop counter.
    new_tokens = int(output_ids.shape[1] - input_ids.shape[1])
    if include_phase_timings:
        return (
            output_ids,
            new_tokens,
            steps,
            float(elapsed),
            acceptance_lengths,
            phase_timings or {},
        )
    return output_ids, new_tokens, steps, float(elapsed), acceptance_lengths


def build_eagle_timing_fields(
    *,
    input_tokens: int,
    output_tokens: int,
    prefill_ms: float | None,
    decode_ms: float | None,
    e2e_ms: float | None,
) -> dict[str, object]:
    """Map EAGLE phase timings into the repository's canonical schema."""

    prefill = float(prefill_ms) if prefill_ms is not None else None
    decode = float(decode_ms) if decode_ms is not None else None
    e2e = float(e2e_ms) if e2e_ms is not None else None
    return {
        "input_tokens": int(input_tokens),
        "output_tokens": int(output_tokens),
        "prefill_ms": round(prefill, 3) if prefill is not None else None,
        "ttft_ms": round(prefill, 3) if prefill is not None else None,
        "decode_ms": round(decode, 3) if decode is not None else None,
        "e2e_ms": round(e2e, 3) if e2e is not None else None,
        "tpot_ms": round(decode / output_tokens, 3)
        if decode is not None and output_tokens > 0
        else None,
        "throughput_tok_s": round(output_tokens / (e2e / 1000.0), 3)
        if e2e is not None and e2e > 0 and output_tokens > 0
        else None,
        "decode_throughput_tok_s": round(output_tokens / (decode / 1000.0), 3)
        if decode is not None and decode > 0 and output_tokens > 0
        else None,
        "measurement_scope": "full_e2e"
        if prefill is not None and e2e is not None
        else "decode_only",
    }


def decode_answer(tokenizer, output_ids: torch.Tensor, input_len: int) -> str:
    return tokenizer.decode(
        output_ids[0, input_len:],
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    ).strip()


def target_logits_parity(
    eagle_target,
    reference_target,
    input_ids: torch.Tensor,
) -> dict[str, float | int | bool]:
    """Compare the vendored KV target with stock Transformers on one prompt."""

    with torch.inference_mode():
        eagle_logits = eagle_target(input_ids, use_cache=False).logits[:, -1, :]
        reference_logits = reference_target(input_ids, use_cache=False).logits[:, -1, :]
    delta = (eagle_logits.float() - reference_logits.float()).abs()
    eagle_top = int(eagle_logits.argmax(dim=-1)[0])
    reference_top = int(reference_logits.argmax(dim=-1)[0])
    return {
        "max_abs_logit_delta": float(delta.max().item()),
        "mean_abs_logit_delta": float(delta.mean().item()),
        "eagle_top_token": eagle_top,
        "reference_top_token": reference_top,
        "top_token_match": eagle_top == reference_top,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-model", required=True)
    parser.add_argument("--eagle-model", required=True)
    parser.add_argument("--question-file", required=True)
    parser.add_argument("--question-begin", type=int, default=0)
    parser.add_argument("--question-end", type=int, default=1)
    parser.add_argument("--num-choices", type=int, default=1)
    parser.add_argument("--max-new-tokens", type=int, default=64)
    parser.add_argument("--max-input-tokens", type=int, default=0,
                        help="truncate each prompt to this many tokens before "
                             "KV cache sizing (0 = no limit; use on T4 smoke runs)")
    parser.add_argument("--total-token", type=int, default=32)
    parser.add_argument("--depth", type=int, default=5)
    parser.add_argument("--top-k", type=int, default=4)
    parser.add_argument("--temperature", type=float, default=0.0)
    parser.add_argument(
        "--seed",
        type=int,
        default=int(os.environ.get("LONG_BENCH_SEED", "42")),
    )
    parser.add_argument("--skip-naive", action="store_true",
                        help="Skip the naive autoregressive baseline (no speedup reported)")
    parser.add_argument("--check-target-parity", action="store_true",
                        help="compare EaModel target logits with stock Transformers once")
    parser.add_argument("--smoke", action="store_true",
                        help="Run exactly one question with a short generation")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    seed_everything(args.seed)

    if args.smoke:
        args.question_end = min(args.question_end, args.question_begin + 1)
        args.max_new_tokens = min(args.max_new_tokens, 32)

    tree_config = resolve_eagle_tree_config(
        total_token=args.total_token,
        depth=args.depth,
        top_k=args.top_k,
    )
    if tree_config["adjusted"]:
        print(
            "[EAGLE3] Adjusting total_token from "
            f"{args.total_token} to {tree_config['total_token']}: "
            f"depth={args.depth}, top_k={args.top_k} can generate at most "
            f"{tree_config['max_total_token']} tree tokens.",
            file=sys.stderr,
        )
        args.total_token = int(tree_config["total_token"])

    if not torch.cuda.is_available():
        raise RuntimeError("EAGLE3 inference requires a visible CUDA GPU")

    # Keep --help and preflight cheap.  The vendored model imports custom
    # attention/KV modules and may trigger CUDA extension discovery.
    from eagle.model.ea_model import EaModel
    from eagle.model.kv_cache import initialize_past_key_values

    questions = load_questions(
        Path(args.question_file), args.question_begin, args.question_end
    )
    print(f"Loaded {len(questions)} questions "
          f"[{args.question_begin}, {args.question_end}), "
          f"{args.num_choices} choice(s) each")

    model = EaModel.from_pretrained(
        base_model_path=args.base_model,
        ea_model_path=args.eagle_model,
        total_token=args.total_token,
        depth=args.depth,
        top_k=args.top_k,
        torch_dtype=torch.float16,
        # Transformers 5's meta-device loader reports a clean state-dict
        # audit for this vendored EAGLE class but leaves its parameters at
        # initialization values.  Materialize the custom target normally so
        # the upstream checkpoint tensors are copied into it.
        low_cpu_mem_usage=False,
        output_loading_info=args.check_target_parity,
        # EAGLE3 builds tree tensors with .tolist(), so CPU/meta offloading
        # from device_map="auto" is not supported here. Keep both models on
        # the single Tesla T4.
        device_map={"": "cuda:0"},
        use_eagle3=True,
    )
    model.eval()
    tokenizer = model.get_tokenizer()

    parity: dict[str, float | int | bool] | None = None
    if args.check_target_parity:
        from transformers import AutoModelForCausalLM

        target_config = model.base_model.config
        target_attention = model.base_model.model.layers[0].self_attn
        if hasattr(target_attention, "_refresh_llama3_rope_buffers"):
            target_attention._refresh_llama3_rope_buffers()
        print(
            "[EAGLE3] target RoPE config:",
            {
                "rope_scaling": getattr(target_config, "rope_scaling", None),
                "rope_parameters": getattr(target_config, "rope_parameters", None),
                "rope_theta": getattr(target_config, "rope_theta", None),
                "rotary_impl": type(target_attention.rotary_emb).__name__,
                "rotary_module": type(target_attention.rotary_emb).__module__,
                "rotary_type": getattr(target_attention.rotary_emb, "rope_type", None),
                "uses_llama3_rope": getattr(target_attention, "_uses_llama3_rope", None),
                "inv_freq_head": target_attention.rotary_emb.inv_freq[:4].detach().float().cpu().tolist(),
            },
        )
        print("Checking vendored EAGLE target logits against stock Transformers ...")
        reference_target = AutoModelForCausalLM.from_pretrained(
            args.base_model,
            dtype=torch.float16,
            attn_implementation="eager",
            low_cpu_mem_usage=True,
        ).to("cuda").eval()
        parity = target_logits_parity(
            model.base_model,
            reference_target,
            build_input_ids(tokenizer, "Hello", "cuda"),
        )
        del reference_target
        torch.cuda.empty_cache()
        print(f"[EAGLE3] target parity: {parity}")

    # Tokenize every prompt up front. This also gives us the longest input so
    # the shared KV cache can be sized to fit *all* questions: EAGLE3 allocates
    # the KV cache only once (on the first generate() call) and then reuses it,
    # so a cache sized for a short warmup would overflow on longer prompts.
    print("Tokenizing prompts ...")
    prompts = [q["turns"][0] for q in questions]
    all_input_ids = [build_input_ids(tokenizer, p, "cuda") for p in prompts]
    if args.max_input_tokens and args.max_input_tokens > 0:
        # Cap long prompts (e.g. govreport) so the EAGLE KV cache and eager
        # attention fit a T4 16GB in smoke runs.
        all_input_ids = [
            truncate_input_ids(t, args.max_input_tokens).contiguous()
            for t in all_input_ids
        ]
    max_input_len = max(t.shape[1] for t in all_input_ids)
    kv_max_length = max_input_len + args.max_new_tokens + args.total_token + 32
    print(f"Max prompt length: {max_input_len}; KV cache max_length: {kv_max_length}")

    past_kv, past_kv_data, cur_len = initialize_past_key_values(
        model.base_model, max_length=kv_max_length
    )
    model.past_key_values = past_kv
    model.past_key_values_data = past_kv_data
    model.current_length_data = cur_len

    # Warm up CUDA kernels (cuBLAS / cuDNN autotune) so the first timed
    # generation is not inflated.
    print("Warming up ...")
    warmup_ids = build_input_ids(tokenizer, "Hello", "cuda")
    with torch.inference_mode():
        model.eagenerate(
            warmup_ids,
            temperature=args.temperature,
            max_new_tokens=8,
            max_length=warmup_ids.shape[1] + 8 + args.total_token + 32,
            log=False,
            is_llama3=True,
        )
        if not args.skip_naive:
            model.naivegenerate(
                warmup_ids,
                temperature=args.temperature,
                max_new_tokens=8,
                max_length=warmup_ids.shape[1] + 8 + args.total_token + 32,
                log=False,
                is_llama3=True,
            )
    print("Warmup done.")

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    records: list[dict] = []
    raw_metrics: list[dict] = []
    with output.open("w", encoding="utf-8") as fout:
        for qi, question in enumerate(questions):
            prompt = question["turns"][0]
            qid = question.get("question_id", qi)
            for choice in range(args.num_choices):
                sample_seed = args.seed
                input_ids = all_input_ids[qi]
                input_len = input_ids.shape[1]

                seed_everything(sample_seed)
                with torch.inference_mode():
                    (
                        out_ids,
                        new_tokens,
                        tree_steps,
                        eagle_time,
                        acceptance_lengths,
                        eagle_phases,
                    ) = timed_generate(
                        model, input_ids, args.temperature,
                        args.max_new_tokens, args.total_token, spec=True,
                        is_llama3=True,
                        include_phase_timings=True,
                    )
                    answer = decode_answer(tokenizer, out_ids, input_len)

                    if not args.skip_naive:
                        seed_everything(sample_seed)
                        (
                            _,
                            naive_tokens,
                            _,
                            naive_time,
                            _,
                            naive_phases,
                        ) = timed_generate(
                            model, input_ids, args.temperature,
                            args.max_new_tokens, args.total_token, spec=False,
                            is_llama3=True,
                            include_phase_timings=True,
                        )
                    else:
                        naive_tokens, naive_time, naive_phases = None, None, {}

                # DFlash reports the unweighted mean of each generation's
                # per-verification acceptance lengths.
                accept_length = (
                    statistics.mean(acceptance_lengths)
                    if acceptance_lengths else 0.0
                )
                eagle_tok_s = new_tokens / eagle_time if eagle_time > 0 else 0.0
                if naive_time is not None and naive_time > 0 and naive_tokens:
                    naive_tok_s = naive_tokens / naive_time
                    speedup = eagle_tok_s / naive_tok_s if naive_tok_s > 0 else 0.0
                else:
                    naive_tok_s, speedup = None, None

                record = {
                    "question_id": qid,
                    "choice": choice,
                    "question": prompt,
                    "answer": answer,
                    "text": answer,
                    "reference_output": question.get("answer") or question.get("reference"),
                    "task_type": question.get("task_type"),
                    "status": "success",
                    "new_tokens": new_tokens,
                    "tree_steps": tree_steps,
                    "accept_length": round(accept_length, 4),
                    "acceptance_lengths": acceptance_lengths,
                    "eagle_time": round(eagle_time, 4),
                    "eagle_tok_s": round(eagle_tok_s, 2),
                    "naive_tokens": naive_tokens,
                    "naive_time": (round(naive_time, 4)
                                   if naive_time is not None else None),
                    "naive_tok_s": (round(naive_tok_s, 2)
                                    if naive_tok_s is not None else None),
                    "speedup": (round(speedup, 3)
                                if speedup is not None else None),
                    "base_model": args.base_model,
                    "eagle_model": args.eagle_model,
                }
                record.update(
                    build_eagle_timing_fields(
                        input_tokens=input_len,
                        output_tokens=new_tokens,
                        prefill_ms=eagle_phases.get("prefill_ms"),
                        decode_ms=eagle_phases.get("decode_ms", eagle_time * 1000.0),
                        e2e_ms=eagle_phases.get("e2e_ms"),
                    )
                )
                record["peak_memory_gb"] = eagle_phases.get("peak_memory_gb")
                record["eagle_phase_timings"] = eagle_phases
                record["naive_phase_timings"] = naive_phases
                reference = question.get("reference") or question.get("answer")
                if record["task_type"] == "code_completion":
                    metrics.add_code_completion(record, answer, reference)
                else:
                    rouge.add_rouge(record, answer, reference)
                records.append(record)
                raw_metrics.append({
                    "eagle_tokens": new_tokens,
                    "eagle_time": eagle_time,
                    "accept_length": accept_length,
                    "naive_tokens": naive_tokens,
                    "naive_time": naive_time,
                })
                fout.write(json.dumps(record, ensure_ascii=False) + "\n")

                print(
                    f"[{qid}] choice={choice} tokens={new_tokens} "
                    f"steps={tree_steps} accept={accept_length:.2f} "
                    f"eagle={eagle_tok_s:.1f} tok/s ({eagle_time:.2f}s)"
                    + (f" | naive={naive_tok_s:.1f} tok/s ({naive_time:.2f}s)"
                       f" | speedup={speedup:.2f}x" if speedup is not None else "")
                )

    # ---- Aggregate statistics -------------------------------------------
    n = len(records)
    total_tokens = sum(r["new_tokens"] for r in records)
    total_steps = sum(r["tree_steps"] for r in records)
    total_eagle_time = sum(r["eagle_time"] for r in raw_metrics)
    eagle_tpot_values = [
        r["eagle_time"] / r["eagle_tokens"]
        for r in raw_metrics
        if r["eagle_tokens"] > 0 and r["eagle_time"] > 0
    ]
    eagle_tpot = statistics.mean(eagle_tpot_values) if eagle_tpot_values else 0.0
    # DFlash defines throughput as the inverse of mean per-generation TPOT,
    # rather than total tokens divided by total time.
    eagle_throughput = 1.0 / eagle_tpot if eagle_tpot > 0 else 0.0

    naive_metrics = [
        r for r in raw_metrics
        if r["naive_tokens"] is not None
        and r["naive_tokens"] > 0
        and r["naive_time"] is not None
        and r["naive_time"] > 0
    ]
    if naive_metrics and not args.skip_naive:
        total_naive_tokens = sum(r["naive_tokens"] for r in naive_metrics)
        total_naive_time = sum(r["naive_time"] for r in naive_metrics)
        naive_tpot_values = [
            r["naive_time"] / r["naive_tokens"] for r in naive_metrics
        ]
        naive_tpot = statistics.mean(naive_tpot_values)
        naive_throughput = 1.0 / naive_tpot if naive_tpot > 0 else 0.0
        # Exact DFlash definition: mean baseline TPOT / mean speculative TPOT.
        speedup = naive_tpot / eagle_tpot if eagle_tpot > 0 else 0.0
        speedups = [
            (r["naive_time"] / r["naive_tokens"])
            / (r["eagle_time"] / r["eagle_tokens"])
            for r in naive_metrics
            if r["eagle_tokens"] > 0 and r["eagle_time"] > 0
        ]
    else:
        total_naive_tokens = None
        total_naive_time, naive_throughput, speedup, speedups = 0.0, None, None, []

    eagle_tok_s_list = [
        r["eagle_tokens"] / r["eagle_time"]
        for r in raw_metrics
        if r["eagle_tokens"] > 0 and r["eagle_time"] > 0
    ]
    accept_lengths = [r["accept_length"] for r in raw_metrics]

    quality = (
        metrics.aggregate_code_completion(records)
        if any(r.get("task_type") == "code_completion" for r in records)
        else rouge.aggregate_rouge(records)
    )
    summary = {
        "type": "summary",
        "num_questions": len(questions),
        "num_generations": n,
        "total_tokens": total_tokens,
        "total_naive_tokens": total_naive_tokens,
        "mean_accept_length": round(
            statistics.mean(accept_lengths), 4) if accept_lengths else 0.0,
        "mean_tree_steps": round(total_steps / n, 2) if n else 0.0,
        "total_eagle_time": round(total_eagle_time, 3),
        "eagle_tok_s": round(eagle_throughput, 2),
        "mean_eagle_tok_s": round(
            statistics.mean(eagle_tok_s_list), 2) if eagle_tok_s_list else 0.0,
        "total_naive_time": (round(total_naive_time, 3)
                             if not args.skip_naive else None),
        "naive_tok_s": (round(naive_throughput, 2)
                        if naive_throughput is not None else None),
        "decoding_speedup": (round(speedup, 3) if speedup is not None else None),
        "mean_speedup": (round(statistics.mean(speedups), 3) if speedups else None),
        **quality,
    }
    with output.open("a", encoding="utf-8") as fout:
        fout.write(json.dumps(summary, ensure_ascii=False) + "\n")

    print("\n" + "=" * 56)
    print("EAGLE3 Decoding Statistics")
    print("=" * 56)
    print(f"Questions            : {len(questions)}")
    print(f"Generations          : {n}")
    print(f"Total output tokens  : {total_tokens}")
    print(f"Mean acceptance len  : {summary['mean_accept_length']:.3f} "
          f"tokens/step")
    print(f"Mean tree steps      : {summary['mean_tree_steps']:.2f}")
    print("-" * 56)
    print(f"EAGLE3 throughput    : {summary['eagle_tok_s']:.2f} tok/s "
          f"({total_eagle_time:.2f}s total)")
    if naive_throughput is not None:
        print(f"Naive throughput     : {naive_throughput:.2f} tok/s "
              f"({total_naive_time:.2f}s total)")
        print(f"Decoding speedup     : {speedup:.2f}x")
    print(f"Mean per-gen EAGLE   : {summary['mean_eagle_tok_s']:.2f} tok/s")
    print("=" * 56)
    print(f"Saved {n} record(s) + summary to: {output}")


if __name__ == "__main__":
    main()
